name: Test-Analyse
on:
  pull_request:
  workflow_dispatch:
jobs:
  Analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jauntin/actions/setup-php-testing@v1
        with:
          php-version: 8.1
      - name: Analyze
        shell: bash
        run: |
          vendor/bin/phpcs
          vendor/bin/phpstan analyse --no-interaction --no-ansi
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo systemctl start mysql.service
      - uses: docker/setup-buildx-action@v2
      - uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - uses: docker/build-push-action@v3
        with:
          context: .
          load: true
          tags: test:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          build-args: |
            ENV=testing
      - run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      - run: cat .github/workflows/scripts/tests.sh | xargs -I {} docker run --rm --net=host test:latest /bin/sh -c '{}'
